language: ruby
rvm:
- 2.5.0
script:
- bundle exec rspec -b spec
- whereis google-chrome-stable
- whereis chromedriver
services:
before_install:
- gem install bundler
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
# - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-arm7hf.tar.gz
# - mkdir geckodriver
# - tar -xzf geckodriver-v0.19.1-arm7hf.tar.gz -C geckodriver
# - export PATH=$PATH:$PWD/geckodriver
# install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
#   - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
#   - unzip ~/chromedriver_linux64.zip -d ~/
#   - rm ~/chromedriver_linux64.zip
#   - sudo mv -f ~/chromedriver /usr/local/share/
#   - sudo chmod +x /usr/local/share/chromedriver
#   - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
deploy:
  provider:
  api_key:
    secure:
  app: appcapella
  on:
    repo: ljcphillips/appcapella
env:
  # - MOZ_HEADLESS=1
addons:
  chrome: stable
