language: ruby
rvm:
- 2.5.0
script:
- bundle exec rspec spec
services:
before_install:
- gem install bundler
before_script:
addons: firefox: "50.0"
deploy:
  provider:
  api_key:
    secure:
  app: appcapella
  on:
    repo: ljcphillips/appcapella
