source 'https://rubygems.org'
ruby '2.5.0'

gem 'capybara'
gem 'puma'
gem 'rack-test'
gem 'rspec'
gem 'selenium-webdriver'
gem 'geckodriver-helper'
gem 'shotgun'
gem 'simplecov'
gem 'simplecov-console'
gem 'sinatra'
