source 'https://rubygems.org'
ruby '2.5.0'

gem 'capybara'
gem 'capybara-selenium'
gem 'puma'
gem 'rack-test'
gem 'rspec'
gem 'selenium-webdriver', '2.53.4'
gem 'shotgun'
gem 'simplecov'
gem 'simplecov-console'
gem 'sinatra', '2.0.2'
